# Generated by Django 4.1.6 on 2023-02-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='profile_img',
            field=models.ImageField(default='man.png', upload_to='User_profiles'),
        ),
    ]
