# Generated by Django 4.1.6 on 2023-02-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_user_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.ImageField(default='no-pictures.png', upload_to='Item_images'),
        ),
    ]
