# Generated by Django 4.1.6 on 2023-02-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_item_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.ImageField(default='cereal.png', upload_to='Category_images'),
        ),
    ]
