# Generated by Django 4.1.6 on 2023-03-10 11:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_alter_item_brand_alter_item_category_sides_meals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField(default=100707)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 3, 10, 14, 59, 29, 478228))),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='meals',
            options={'ordering': ('name',), 'verbose_name_plural': 'Meals'},
        ),
        migrations.AlterModelOptions(
            name='sides',
            options={'ordering': ('name',), 'verbose_name_plural': 'Sides'},
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField(max_length=30)),
                ('item_price', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Inventory.order')),
            ],
            options={
                'verbose_name_plural': 'Order Items',
                'ordering': ('order',),
            },
        ),
    ]
