# Generated by Django 4.1.6 on 2023-03-10 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_order_alter_meals_options_alter_sides_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='item_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 15, 50, 19, 519279)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.IntegerField(default=967485),
        ),
    ]
