# Generated by Django 4.1.6 on 2023-03-10 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_orderitems_item_quantity_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='unique_id',
            field=models.IntegerField(default=812977),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 16, 31, 32, 845010)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.IntegerField(default=763067),
        ),
    ]
