# Generated by Django 4.1.6 on 2023-03-18 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_orderitems_unique_id_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 9, 8, 41, 345805)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='unique_id',
            field=models.IntegerField(default=103058),
        ),
    ]
