# Generated by Django 4.1.6 on 2023-03-18 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_order_total_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 9, 26, 17, 318861)),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='unique_id',
            field=models.IntegerField(default=179789, unique=True),
        ),
    ]
